export const TOUTES_TRIBUNAUX: string[] = [
  'TPI Abengourou',
  'TPI Abidjan (Plateau)',
  'TPI Abidjan-Yopougon',
  'TPI Aboisso',
  'TPI Bondoukou',
  'TPI Bouaké',
  'TPI Bouna',
  'TPI Boundiali',
  'TPI Daloa',
  'TPI Dimbokro',
  'TPI Divo',
  'TPI Ferkessédougou',
  'TPI Gagnoa',
  'TPI Guiglo',
  'TPI Katiola',
  'TPI Korhogo',
  'TPI Man',
  'TPI Odienné',
  'TPI San-Pédro',
  'TPI Sassandra',
  'TPI Séguéla',
  'TPI Soubré',
  'TPI Touba',
  'TPI Toumodi'
];
